server:
  port: 8600

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_stage_db
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true

logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus    # Exponer solo lo necesario
  endpoint:
    health:
      show-details: always                 # Peticiones detalladas para Grafana
  metrics:
    export:
      prometheus:
        enabled: true                      # Activa /actuator/prometheus
